# -*-python-*-

import os

env = Environment(tools = ['toolchain'])

env.AppendUnique(LIBS = [])
env.AppendUnique(CPPDEFINES=['MESSAGE'])

if env['SYSTEM'] == 'linux':
    env.AppendUnique(CCFLAGS=['-Wno-deprecated-declarations'])
VariantDir(os.path.join('build', 'src'), 'src')

SConscript(os.path.join('build', 'src', 'cpp', 'SConscript'), exports="env")
SConscript(os.path.join('build', 'src', 'py', 'wrapper', 'SConscript'), exports="env")

Default("install")