package:
  name: python-sequence_analysis
  version: "1.0.0"

source:
  path: ../../..

build:
  number: 0

about:
  home:  http://openalea.gforge.inria.fr/doc/vplants/sequence/doc/html/contents.html
  license: CeCILL-C

requirements:
  build:
    - libtoolchain
    - python-toolchain
    - libboost_python-dev
    - libsequence_analysis
    - python
  run:
    - libsequence_analysis
    - python
    - multipledispatch