package:
    name: libsequence_analysis
    version: "1.0.0"

source:
    path: ../../..

build:
    number: 0
    
about:
    home: http://openalea.gforge.inria.fr/doc/vplants/sequence_analysis/doc/html/contents.html
    license: CeCILL-C

requirements:
    build:
        - libtoolchain
        - libboost_core-dev
        - libstat_tool
    run:
        - libboost
        - libstat_tool
