# -*-python-*-

from SCons.Errors import EnvironmentError

try:
    Import("env")

    cppenv = env.Clone(tools = ['cpp'])

    cppenv.AppendUnique(CPPDEFINES = ['LIBSEQUENCE_ANALYSIS'])
    cppenv.AppendUnique(LIBS = ['stat_tool'])
    exclude = """
    """.split()

    sources = [source for source in cppenv.Glob('*.h*') if not source.name in exclude]
    targets = cppenv.CppDev("sequence_analysis", sources)
    Alias("cpp-dev", targets)
    Alias("cpp", targets)
    Alias("install", targets)

    exclude = """
    """.split()

    sources = [source for source in cppenv.Glob('*.cpp') if not source.name in exclude]
    targets = cppenv.CppLib("sequence_analysis", sources)
    Alias("cpp-lib", targets)
    Alias("cpp", targets)
    Alias("install", targets)
except EnvironmentError:
    Alias("cpp-dev", [])
    Alias("cpp-lib", [])
    Alias("cpp", [])
    Alias("install", [])
    pass
except Exception:
    raise