# -*-python-*-

import os

env = Environment(tools = ['toolchain'])

# env.AppendUnique(LIBS = ['stat_tool'])
env.AppendUnique(CPPDEFINES=['MESSAGE'])

VariantDir(os.path.join('build', 'src'), 'src')

SConscript(os.path.join('build', 'src', 'cpp', 'SConscript'), exports="env")
SConscript(os.path.join('build', 'src', 'py', 'wrapper', 'SConscript'), exports="env")

Default("install")